/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint32Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint32StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEaddressStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEaddressStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export declare namespace SilentVault {
  export type BeneficiaryStruct = {
    wallet: AddressLike;
    shareBps: BigNumberish;
  };

  export type BeneficiaryStructOutput = [wallet: string, shareBps: bigint] & {
    wallet: string;
    shareBps: bigint;
  };

  export type VaultViewStruct = {
    id: BigNumberish;
    owner: AddressLike;
    label: string;
    createdAt: BigNumberish;
    inactivityPeriod: BigNumberish;
    gracePeriod: BigNumberish;
    lastCheckIn: BigNumberish;
    triggerStartedAt: BigNumberish;
    emergencyMode: boolean;
    unlocked: boolean;
    encryptedPayload: string;
    payloadHash: BytesLike;
    beneficiaryCount: BigNumberish;
  };

  export type VaultViewStructOutput = [
    id: bigint,
    owner: string,
    label: string,
    createdAt: bigint,
    inactivityPeriod: bigint,
    gracePeriod: bigint,
    lastCheckIn: bigint,
    triggerStartedAt: bigint,
    emergencyMode: boolean,
    unlocked: boolean,
    encryptedPayload: string,
    payloadHash: string,
    beneficiaryCount: bigint
  ] & {
    id: bigint;
    owner: string;
    label: string;
    createdAt: bigint;
    inactivityPeriod: bigint;
    gracePeriod: bigint;
    lastCheckIn: bigint;
    triggerStartedAt: bigint;
    emergencyMode: boolean;
    unlocked: boolean;
    encryptedPayload: string;
    payloadHash: string;
    beneficiaryCount: bigint;
  };
}

export interface SilentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_BENEFICIARIES"
      | "canUnlock"
      | "cancelRecovery"
      | "checkIn"
      | "createVault"
      | "getBeneficiaries"
      | "getEncryptedHandles"
      | "getVault"
      | "getVaultsByBeneficiary"
      | "getVaultsByOwner"
      | "grantUnlockedAccess"
      | "isRecoveryReady"
      | "isVaultBeneficiary"
      | "startRecovery"
      | "triggerEmergency"
      | "unlockVault"
      | "vaultCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CheckIn"
      | "RecoveryCancelled"
      | "RecoveryStarted"
      | "VaultCreated"
      | "VaultUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BENEFICIARIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canUnlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecovery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [
      string,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      string,
      BytesLike,
      InEuint64Struct,
      InEuint32Struct,
      InEaddressStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHandles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsByBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantUnlockedAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRecoveryReady",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultBeneficiary",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startRecovery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerEmergency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BENEFICIARIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canUnlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsByBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantUnlockedAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRecoveryReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVaultBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultCount", data: BytesLike): Result;
}

export namespace CheckInEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [vaultId: bigint, owner: string, timestamp: bigint];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCancelledEvent {
  export type InputTuple = [vaultId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [vaultId: bigint, owner: string];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryStartedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    actor: AddressLike,
    unlocksAt: BigNumberish,
    emergencyMode: boolean
  ];
  export type OutputTuple = [
    vaultId: bigint,
    actor: string,
    unlocksAt: bigint,
    emergencyMode: boolean
  ];
  export interface OutputObject {
    vaultId: bigint;
    actor: string;
    unlocksAt: bigint;
    emergencyMode: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    payloadHash: BytesLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    owner: string,
    payloadHash: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    payloadHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnlockedEvent {
  export type InputTuple = [vaultId: BigNumberish, actor: AddressLike];
  export type OutputTuple = [vaultId: bigint, actor: string];
  export interface OutputObject {
    vaultId: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SilentVault extends BaseContract {
  connect(runner?: ContractRunner | null): SilentVault;
  waitForDeployment(): Promise<this>;

  interface: SilentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_BENEFICIARIES: TypedContractMethod<[], [bigint], "view">;

  canUnlock: TypedContractMethod<[vaultId: BigNumberish], [boolean], "view">;

  cancelRecovery: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkIn: TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;

  createVault: TypedContractMethod<
    [
      label: string,
      beneficiaryWallets: AddressLike[],
      sharesBps: BigNumberish[],
      inactivityPeriod: BigNumberish,
      gracePeriod: BigNumberish,
      encryptedPayload: string,
      payloadHash: BytesLike,
      releaseCodeInput: InEuint64Struct,
      assetCountInput: InEuint32Struct,
      primaryBeneficiaryInput: InEaddressStruct
    ],
    [bigint],
    "nonpayable"
  >;

  getBeneficiaries: TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.BeneficiaryStructOutput[]],
    "view"
  >;

  getEncryptedHandles: TypedContractMethod<
    [vaultId: BigNumberish],
    [
      [string, string, string] & {
        releaseCode: string;
        assetCount: string;
        primaryBeneficiary: string;
      }
    ],
    "view"
  >;

  getVault: TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.VaultViewStructOutput],
    "view"
  >;

  getVaultsByBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint[]],
    "view"
  >;

  getVaultsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  grantUnlockedAccess: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  isRecoveryReady: TypedContractMethod<
    [vaultId: BigNumberish],
    [boolean],
    "view"
  >;

  isVaultBeneficiary: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  startRecovery: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  triggerEmergency: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockVault: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  vaultCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BENEFICIARIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canUnlock"
  ): TypedContractMethod<[vaultId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelRecovery"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      label: string,
      beneficiaryWallets: AddressLike[],
      sharesBps: BigNumberish[],
      inactivityPeriod: BigNumberish,
      gracePeriod: BigNumberish,
      encryptedPayload: string,
      payloadHash: BytesLike,
      releaseCodeInput: InEuint64Struct,
      assetCountInput: InEuint32Struct,
      primaryBeneficiaryInput: InEaddressStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaries"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.BeneficiaryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedHandles"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [
      [string, string, string] & {
        releaseCode: string;
        assetCount: string;
        primaryBeneficiary: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.VaultViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultsByBeneficiary"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVaultsByOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantUnlockedAccess"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isRecoveryReady"
  ): TypedContractMethod<[vaultId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVaultBeneficiary"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "startRecovery"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerEmergency"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockVault"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vaultCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CheckIn"
  ): TypedContractEvent<
    CheckInEvent.InputTuple,
    CheckInEvent.OutputTuple,
    CheckInEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCancelled"
  ): TypedContractEvent<
    RecoveryCancelledEvent.InputTuple,
    RecoveryCancelledEvent.OutputTuple,
    RecoveryCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryStarted"
  ): TypedContractEvent<
    RecoveryStartedEvent.InputTuple,
    RecoveryStartedEvent.OutputTuple,
    RecoveryStartedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnlocked"
  ): TypedContractEvent<
    VaultUnlockedEvent.InputTuple,
    VaultUnlockedEvent.OutputTuple,
    VaultUnlockedEvent.OutputObject
  >;

  filters: {
    "CheckIn(uint256,address,uint64)": TypedContractEvent<
      CheckInEvent.InputTuple,
      CheckInEvent.OutputTuple,
      CheckInEvent.OutputObject
    >;
    CheckIn: TypedContractEvent<
      CheckInEvent.InputTuple,
      CheckInEvent.OutputTuple,
      CheckInEvent.OutputObject
    >;

    "RecoveryCancelled(uint256,address)": TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;
    RecoveryCancelled: TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;

    "RecoveryStarted(uint256,address,uint64,bool)": TypedContractEvent<
      RecoveryStartedEvent.InputTuple,
      RecoveryStartedEvent.OutputTuple,
      RecoveryStartedEvent.OutputObject
    >;
    RecoveryStarted: TypedContractEvent<
      RecoveryStartedEvent.InputTuple,
      RecoveryStartedEvent.OutputTuple,
      RecoveryStartedEvent.OutputObject
    >;

    "VaultCreated(uint256,address,bytes32)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultUnlocked(uint256,address)": TypedContractEvent<
      VaultUnlockedEvent.InputTuple,
      VaultUnlockedEvent.OutputTuple,
      VaultUnlockedEvent.OutputObject
    >;
    VaultUnlocked: TypedContractEvent<
      VaultUnlockedEvent.InputTuple,
      VaultUnlockedEvent.OutputTuple,
      VaultUnlockedEvent.OutputObject
    >;
  };
}
