/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint32Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint32StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEaddressStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEaddressStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export declare namespace SilentVault {
  export type VaultPolicyInputStruct = {
    inactivityPeriod: BigNumberish;
    gracePeriod: BigNumberish;
    approvalThreshold: BigNumberish;
  };

  export type VaultPolicyInputStructOutput = [
    inactivityPeriod: bigint,
    gracePeriod: bigint,
    approvalThreshold: bigint
  ] & {
    inactivityPeriod: bigint;
    gracePeriod: bigint;
    approvalThreshold: bigint;
  };

  export type VaultMetadataInputStruct = {
    encryptedPayload: string;
    payloadHash: BytesLike;
    externalPayloadCid: string;
    externalPayloadHash: BytesLike;
    notificationHash: BytesLike;
    proofOfLifeHash: BytesLike;
  };

  export type VaultMetadataInputStructOutput = [
    encryptedPayload: string,
    payloadHash: string,
    externalPayloadCid: string,
    externalPayloadHash: string,
    notificationHash: string,
    proofOfLifeHash: string
  ] & {
    encryptedPayload: string;
    payloadHash: string;
    externalPayloadCid: string;
    externalPayloadHash: string;
    notificationHash: string;
    proofOfLifeHash: string;
  };

  export type BeneficiaryStruct = {
    wallet: AddressLike;
    shareBps: BigNumberish;
  };

  export type BeneficiaryStructOutput = [wallet: string, shareBps: bigint] & {
    wallet: string;
    shareBps: bigint;
  };

  export type VaultViewStruct = {
    id: BigNumberish;
    owner: AddressLike;
    label: string;
    createdAt: BigNumberish;
    inactivityPeriod: BigNumberish;
    gracePeriod: BigNumberish;
    lastCheckIn: BigNumberish;
    triggerStartedAt: BigNumberish;
    emergencyMode: boolean;
    unlocked: boolean;
    encryptedPayload: string;
    payloadHash: BytesLike;
    beneficiaryCount: BigNumberish;
    approvalThreshold: BigNumberish;
    recoveryApprovals: BigNumberish;
    hiddenBeneficiaries: boolean;
    externalPayloadCid: string;
    externalPayloadHash: BytesLike;
    notificationHash: BytesLike;
    proofOfLifeHash: BytesLike;
  };

  export type VaultViewStructOutput = [
    id: bigint,
    owner: string,
    label: string,
    createdAt: bigint,
    inactivityPeriod: bigint,
    gracePeriod: bigint,
    lastCheckIn: bigint,
    triggerStartedAt: bigint,
    emergencyMode: boolean,
    unlocked: boolean,
    encryptedPayload: string,
    payloadHash: string,
    beneficiaryCount: bigint,
    approvalThreshold: bigint,
    recoveryApprovals: bigint,
    hiddenBeneficiaries: boolean,
    externalPayloadCid: string,
    externalPayloadHash: string,
    notificationHash: string,
    proofOfLifeHash: string
  ] & {
    id: bigint;
    owner: string;
    label: string;
    createdAt: bigint;
    inactivityPeriod: bigint;
    gracePeriod: bigint;
    lastCheckIn: bigint;
    triggerStartedAt: bigint;
    emergencyMode: boolean;
    unlocked: boolean;
    encryptedPayload: string;
    payloadHash: string;
    beneficiaryCount: bigint;
    approvalThreshold: bigint;
    recoveryApprovals: bigint;
    hiddenBeneficiaries: boolean;
    externalPayloadCid: string;
    externalPayloadHash: string;
    notificationHash: string;
    proofOfLifeHash: string;
  };
}

export interface SilentVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BPS_DENOMINATOR"
      | "MAX_BENEFICIARIES"
      | "approveRecovery"
      | "canUnlock"
      | "cancelRecovery"
      | "checkIn"
      | "computeHiddenBeneficiaryCommitment"
      | "createVault"
      | "createVaultAdvanced"
      | "getBeneficiaries"
      | "getEncryptedHandles"
      | "getHiddenBeneficiaryCommitments"
      | "getVault"
      | "getVaultsByBeneficiary"
      | "getVaultsByOwner"
      | "grantUnlockedAccess"
      | "hasApprovedRecovery"
      | "isRecoveryReady"
      | "isVaultBeneficiary"
      | "revealHiddenBeneficiary"
      | "rotateBeneficiary"
      | "rotateHiddenBeneficiaryCommitment"
      | "startRecovery"
      | "triggerEmergency"
      | "unlockVault"
      | "updateVaultMetadata"
      | "vaultCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryRotated"
      | "CheckIn"
      | "HiddenBeneficiaryRevealed"
      | "HiddenBeneficiaryRotated"
      | "RecoveryApproved"
      | "RecoveryCancelled"
      | "RecoveryStarted"
      | "VaultCreated"
      | "VaultMetadataUpdated"
      | "VaultUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BPS_DENOMINATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BENEFICIARIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveRecovery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canUnlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecovery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "computeHiddenBeneficiaryCommitment",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [
      string,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      string,
      BytesLike,
      InEuint64Struct,
      InEuint32Struct,
      InEaddressStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createVaultAdvanced",
    values: [
      string,
      AddressLike[],
      BigNumberish[],
      BytesLike[],
      BigNumberish[],
      SilentVault.VaultPolicyInputStruct,
      SilentVault.VaultMetadataInputStruct,
      InEuint64Struct,
      InEuint32Struct,
      InEaddressStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiaries",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedHandles",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHiddenBeneficiaryCommitments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsByBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultsByOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantUnlockedAccess",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApprovedRecovery",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRecoveryReady",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVaultBeneficiary",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revealHiddenBeneficiary",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateBeneficiary",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rotateHiddenBeneficiaryCommitment",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startRecovery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerEmergency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockVault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVaultMetadata",
    values: [
      BigNumberish,
      string,
      BytesLike,
      string,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "BPS_DENOMINATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BENEFICIARIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canUnlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "computeHiddenBeneficiaryCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVaultAdvanced",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedHandles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHiddenBeneficiaryCommitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsByBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultsByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantUnlockedAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasApprovedRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRecoveryReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVaultBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealHiddenBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotateBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rotateHiddenBeneficiaryCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVaultMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultCount", data: BytesLike): Result;
}

export namespace BeneficiaryRotatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    oldWallet: AddressLike,
    newWallet: AddressLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    owner: string,
    oldWallet: string,
    newWallet: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    oldWallet: string;
    newWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CheckInEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [vaultId: bigint, owner: string, timestamp: bigint];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HiddenBeneficiaryRevealedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    beneficiary: AddressLike,
    commitment: BytesLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    beneficiary: string,
    commitment: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    beneficiary: string;
    commitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HiddenBeneficiaryRotatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    oldCommitment: BytesLike,
    newCommitment: BytesLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    owner: string,
    oldCommitment: string,
    newCommitment: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    oldCommitment: string;
    newCommitment: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryApprovedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    actor: AddressLike,
    approvals: BigNumberish,
    threshold: BigNumberish
  ];
  export type OutputTuple = [
    vaultId: bigint,
    actor: string,
    approvals: bigint,
    threshold: bigint
  ];
  export interface OutputObject {
    vaultId: bigint;
    actor: string;
    approvals: bigint;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCancelledEvent {
  export type InputTuple = [vaultId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [vaultId: bigint, owner: string];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryStartedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    actor: AddressLike,
    unlocksAt: BigNumberish,
    emergencyMode: boolean
  ];
  export type OutputTuple = [
    vaultId: bigint,
    actor: string,
    unlocksAt: bigint,
    emergencyMode: boolean
  ];
  export interface OutputObject {
    vaultId: bigint;
    actor: string;
    unlocksAt: bigint;
    emergencyMode: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    owner: AddressLike,
    payloadHash: BytesLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    owner: string,
    payloadHash: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    owner: string;
    payloadHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultMetadataUpdatedEvent {
  export type InputTuple = [
    vaultId: BigNumberish,
    payloadHash: BytesLike,
    externalPayloadHash: BytesLike,
    notificationHash: BytesLike,
    proofOfLifeHash: BytesLike
  ];
  export type OutputTuple = [
    vaultId: bigint,
    payloadHash: string,
    externalPayloadHash: string,
    notificationHash: string,
    proofOfLifeHash: string
  ];
  export interface OutputObject {
    vaultId: bigint;
    payloadHash: string;
    externalPayloadHash: string;
    notificationHash: string;
    proofOfLifeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUnlockedEvent {
  export type InputTuple = [vaultId: BigNumberish, actor: AddressLike];
  export type OutputTuple = [vaultId: bigint, actor: string];
  export interface OutputObject {
    vaultId: bigint;
    actor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SilentVault extends BaseContract {
  connect(runner?: ContractRunner | null): SilentVault;
  waitForDeployment(): Promise<this>;

  interface: SilentVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BPS_DENOMINATOR: TypedContractMethod<[], [bigint], "view">;

  MAX_BENEFICIARIES: TypedContractMethod<[], [bigint], "view">;

  approveRecovery: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  canUnlock: TypedContractMethod<[vaultId: BigNumberish], [boolean], "view">;

  cancelRecovery: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkIn: TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;

  computeHiddenBeneficiaryCommitment: TypedContractMethod<
    [wallet: AddressLike, salt: BytesLike],
    [string],
    "view"
  >;

  createVault: TypedContractMethod<
    [
      label: string,
      beneficiaryWallets: AddressLike[],
      sharesBps: BigNumberish[],
      inactivityPeriod: BigNumberish,
      gracePeriod: BigNumberish,
      encryptedPayload: string,
      payloadHash: BytesLike,
      releaseCodeInput: InEuint64Struct,
      assetCountInput: InEuint32Struct,
      primaryBeneficiaryInput: InEaddressStruct
    ],
    [bigint],
    "nonpayable"
  >;

  createVaultAdvanced: TypedContractMethod<
    [
      label: string,
      beneficiaryWallets: AddressLike[],
      sharesBps: BigNumberish[],
      hiddenBeneficiaryCommitments: BytesLike[],
      hiddenSharesBps: BigNumberish[],
      policy: SilentVault.VaultPolicyInputStruct,
      metadata: SilentVault.VaultMetadataInputStruct,
      releaseCodeInput: InEuint64Struct,
      assetCountInput: InEuint32Struct,
      primaryBeneficiaryInput: InEaddressStruct
    ],
    [bigint],
    "nonpayable"
  >;

  getBeneficiaries: TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.BeneficiaryStructOutput[]],
    "view"
  >;

  getEncryptedHandles: TypedContractMethod<
    [vaultId: BigNumberish],
    [
      [string, string, string] & {
        releaseCode: string;
        assetCount: string;
        primaryBeneficiary: string;
      }
    ],
    "view"
  >;

  getHiddenBeneficiaryCommitments: TypedContractMethod<
    [vaultId: BigNumberish],
    [string[]],
    "view"
  >;

  getVault: TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.VaultViewStructOutput],
    "view"
  >;

  getVaultsByBeneficiary: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint[]],
    "view"
  >;

  getVaultsByOwner: TypedContractMethod<
    [owner: AddressLike],
    [bigint[]],
    "view"
  >;

  grantUnlockedAccess: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasApprovedRecovery: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isRecoveryReady: TypedContractMethod<
    [vaultId: BigNumberish],
    [boolean],
    "view"
  >;

  isVaultBeneficiary: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  revealHiddenBeneficiary: TypedContractMethod<
    [vaultId: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;

  rotateBeneficiary: TypedContractMethod<
    [vaultId: BigNumberish, oldWallet: AddressLike, newWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  rotateHiddenBeneficiaryCommitment: TypedContractMethod<
    [vaultId: BigNumberish, oldCommitment: BytesLike, newCommitment: BytesLike],
    [void],
    "nonpayable"
  >;

  startRecovery: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  triggerEmergency: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockVault: TypedContractMethod<
    [vaultId: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateVaultMetadata: TypedContractMethod<
    [
      vaultId: BigNumberish,
      encryptedPayload: string,
      payloadHash: BytesLike,
      externalPayloadCid: string,
      externalPayloadHash: BytesLike,
      notificationHash: BytesLike,
      proofOfLifeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  vaultCount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BPS_DENOMINATOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BENEFICIARIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveRecovery"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canUnlock"
  ): TypedContractMethod<[vaultId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelRecovery"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "computeHiddenBeneficiaryCommitment"
  ): TypedContractMethod<
    [wallet: AddressLike, salt: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      label: string,
      beneficiaryWallets: AddressLike[],
      sharesBps: BigNumberish[],
      inactivityPeriod: BigNumberish,
      gracePeriod: BigNumberish,
      encryptedPayload: string,
      payloadHash: BytesLike,
      releaseCodeInput: InEuint64Struct,
      assetCountInput: InEuint32Struct,
      primaryBeneficiaryInput: InEaddressStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVaultAdvanced"
  ): TypedContractMethod<
    [
      label: string,
      beneficiaryWallets: AddressLike[],
      sharesBps: BigNumberish[],
      hiddenBeneficiaryCommitments: BytesLike[],
      hiddenSharesBps: BigNumberish[],
      policy: SilentVault.VaultPolicyInputStruct,
      metadata: SilentVault.VaultMetadataInputStruct,
      releaseCodeInput: InEuint64Struct,
      assetCountInput: InEuint32Struct,
      primaryBeneficiaryInput: InEaddressStruct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBeneficiaries"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.BeneficiaryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedHandles"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [
      [string, string, string] & {
        releaseCode: string;
        assetCount: string;
        primaryBeneficiary: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHiddenBeneficiaryCommitments"
  ): TypedContractMethod<[vaultId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getVault"
  ): TypedContractMethod<
    [vaultId: BigNumberish],
    [SilentVault.VaultViewStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultsByBeneficiary"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVaultsByOwner"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "grantUnlockedAccess"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasApprovedRecovery"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRecoveryReady"
  ): TypedContractMethod<[vaultId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVaultBeneficiary"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealHiddenBeneficiary"
  ): TypedContractMethod<
    [vaultId: BigNumberish, salt: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateBeneficiary"
  ): TypedContractMethod<
    [vaultId: BigNumberish, oldWallet: AddressLike, newWallet: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rotateHiddenBeneficiaryCommitment"
  ): TypedContractMethod<
    [vaultId: BigNumberish, oldCommitment: BytesLike, newCommitment: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startRecovery"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerEmergency"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unlockVault"
  ): TypedContractMethod<[vaultId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVaultMetadata"
  ): TypedContractMethod<
    [
      vaultId: BigNumberish,
      encryptedPayload: string,
      payloadHash: BytesLike,
      externalPayloadCid: string,
      externalPayloadHash: BytesLike,
      notificationHash: BytesLike,
      proofOfLifeHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vaultCount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BeneficiaryRotated"
  ): TypedContractEvent<
    BeneficiaryRotatedEvent.InputTuple,
    BeneficiaryRotatedEvent.OutputTuple,
    BeneficiaryRotatedEvent.OutputObject
  >;
  getEvent(
    key: "CheckIn"
  ): TypedContractEvent<
    CheckInEvent.InputTuple,
    CheckInEvent.OutputTuple,
    CheckInEvent.OutputObject
  >;
  getEvent(
    key: "HiddenBeneficiaryRevealed"
  ): TypedContractEvent<
    HiddenBeneficiaryRevealedEvent.InputTuple,
    HiddenBeneficiaryRevealedEvent.OutputTuple,
    HiddenBeneficiaryRevealedEvent.OutputObject
  >;
  getEvent(
    key: "HiddenBeneficiaryRotated"
  ): TypedContractEvent<
    HiddenBeneficiaryRotatedEvent.InputTuple,
    HiddenBeneficiaryRotatedEvent.OutputTuple,
    HiddenBeneficiaryRotatedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryApproved"
  ): TypedContractEvent<
    RecoveryApprovedEvent.InputTuple,
    RecoveryApprovedEvent.OutputTuple,
    RecoveryApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCancelled"
  ): TypedContractEvent<
    RecoveryCancelledEvent.InputTuple,
    RecoveryCancelledEvent.OutputTuple,
    RecoveryCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryStarted"
  ): TypedContractEvent<
    RecoveryStartedEvent.InputTuple,
    RecoveryStartedEvent.OutputTuple,
    RecoveryStartedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultMetadataUpdated"
  ): TypedContractEvent<
    VaultMetadataUpdatedEvent.InputTuple,
    VaultMetadataUpdatedEvent.OutputTuple,
    VaultMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUnlocked"
  ): TypedContractEvent<
    VaultUnlockedEvent.InputTuple,
    VaultUnlockedEvent.OutputTuple,
    VaultUnlockedEvent.OutputObject
  >;

  filters: {
    "BeneficiaryRotated(uint256,address,address,address)": TypedContractEvent<
      BeneficiaryRotatedEvent.InputTuple,
      BeneficiaryRotatedEvent.OutputTuple,
      BeneficiaryRotatedEvent.OutputObject
    >;
    BeneficiaryRotated: TypedContractEvent<
      BeneficiaryRotatedEvent.InputTuple,
      BeneficiaryRotatedEvent.OutputTuple,
      BeneficiaryRotatedEvent.OutputObject
    >;

    "CheckIn(uint256,address,uint64)": TypedContractEvent<
      CheckInEvent.InputTuple,
      CheckInEvent.OutputTuple,
      CheckInEvent.OutputObject
    >;
    CheckIn: TypedContractEvent<
      CheckInEvent.InputTuple,
      CheckInEvent.OutputTuple,
      CheckInEvent.OutputObject
    >;

    "HiddenBeneficiaryRevealed(uint256,address,bytes32)": TypedContractEvent<
      HiddenBeneficiaryRevealedEvent.InputTuple,
      HiddenBeneficiaryRevealedEvent.OutputTuple,
      HiddenBeneficiaryRevealedEvent.OutputObject
    >;
    HiddenBeneficiaryRevealed: TypedContractEvent<
      HiddenBeneficiaryRevealedEvent.InputTuple,
      HiddenBeneficiaryRevealedEvent.OutputTuple,
      HiddenBeneficiaryRevealedEvent.OutputObject
    >;

    "HiddenBeneficiaryRotated(uint256,address,bytes32,bytes32)": TypedContractEvent<
      HiddenBeneficiaryRotatedEvent.InputTuple,
      HiddenBeneficiaryRotatedEvent.OutputTuple,
      HiddenBeneficiaryRotatedEvent.OutputObject
    >;
    HiddenBeneficiaryRotated: TypedContractEvent<
      HiddenBeneficiaryRotatedEvent.InputTuple,
      HiddenBeneficiaryRotatedEvent.OutputTuple,
      HiddenBeneficiaryRotatedEvent.OutputObject
    >;

    "RecoveryApproved(uint256,address,uint8,uint8)": TypedContractEvent<
      RecoveryApprovedEvent.InputTuple,
      RecoveryApprovedEvent.OutputTuple,
      RecoveryApprovedEvent.OutputObject
    >;
    RecoveryApproved: TypedContractEvent<
      RecoveryApprovedEvent.InputTuple,
      RecoveryApprovedEvent.OutputTuple,
      RecoveryApprovedEvent.OutputObject
    >;

    "RecoveryCancelled(uint256,address)": TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;
    RecoveryCancelled: TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;

    "RecoveryStarted(uint256,address,uint64,bool)": TypedContractEvent<
      RecoveryStartedEvent.InputTuple,
      RecoveryStartedEvent.OutputTuple,
      RecoveryStartedEvent.OutputObject
    >;
    RecoveryStarted: TypedContractEvent<
      RecoveryStartedEvent.InputTuple,
      RecoveryStartedEvent.OutputTuple,
      RecoveryStartedEvent.OutputObject
    >;

    "VaultCreated(uint256,address,bytes32)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultMetadataUpdated(uint256,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      VaultMetadataUpdatedEvent.InputTuple,
      VaultMetadataUpdatedEvent.OutputTuple,
      VaultMetadataUpdatedEvent.OutputObject
    >;
    VaultMetadataUpdated: TypedContractEvent<
      VaultMetadataUpdatedEvent.InputTuple,
      VaultMetadataUpdatedEvent.OutputTuple,
      VaultMetadataUpdatedEvent.OutputObject
    >;

    "VaultUnlocked(uint256,address)": TypedContractEvent<
      VaultUnlockedEvent.InputTuple,
      VaultUnlockedEvent.OutputTuple,
      VaultUnlockedEvent.OutputObject
    >;
    VaultUnlocked: TypedContractEvent<
      VaultUnlockedEvent.InputTuple,
      VaultUnlockedEvent.OutputTuple,
      VaultUnlockedEvent.OutputObject
    >;
  };
}
