// SPDX-License-Identifier: UNLICENSED
// Auto-generated by @cofhe/hardhat-plugin — do not edit.
// Importing mock contracts here causes Hardhat to compile them and register
// their artifacts, enabling proper revert decoding during tests.
pragma solidity >=0.8.25 <0.9.0;

import "@cofhe/mock-contracts/contracts/ABITest.sol";
import "@cofhe/mock-contracts/contracts/MockACL.sol";
import "@cofhe/mock-contracts/contracts/MockCoFHE.sol";
import "@cofhe/mock-contracts/contracts/MockTaskManager.sol";
import "@cofhe/mock-contracts/contracts/MockThresholdNetwork.sol";
import "@cofhe/mock-contracts/contracts/MockZkVerifier.sol";
import "@cofhe/mock-contracts/contracts/Permissioned.sol";
import "@cofhe/mock-contracts/contracts/TestBed.sol";
