/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type InEuint8Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint8StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint16Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint16StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint32Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint32StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEuint128Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint128StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEboolStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEboolStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export type InEaddressStruct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEaddressStructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export declare namespace ABITest {
  export type ContainsEncryptedResultStruct = {
    value: BigNumberish;
    encryptedResult: BytesLike;
  };

  export type ContainsEncryptedResultStructOutput = [
    value: bigint,
    encryptedResult: string
  ] & { value: bigint; encryptedResult: string };

  export type ContainsEncryptedInputStruct = {
    value: BigNumberish;
    encryptedInput: InEuint32Struct;
  };

  export type ContainsEncryptedInputStructOutput = [
    value: bigint,
    encryptedInput: InEuint32StructOutput
  ] & { value: bigint; encryptedInput: InEuint32StructOutput };
}

export interface ABITestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "eAddress"
      | "eBool"
      | "eNumber"
      | "eUint128"
      | "eUint16"
      | "eUint32"
      | "eUint64"
      | "eUint8"
      | "fnAllEncryptedInputs"
      | "fnArrayContainsEncryptedInput"
      | "fnBlendedInputsIncludingEncryptedInput"
      | "fnEncryptedInput"
      | "fnNoEncryptedInputs"
      | "fnReturnAllEncrypted"
      | "fnReturnBlendedIncludingEncrypted"
      | "fnReturnEncrypted"
      | "fnReturnEncryptedArray"
      | "fnReturnEncryptedStruct"
      | "fnReturnNoEncrypted"
      | "fnStructContainsEncryptedInput"
      | "fnTupleContainsEncryptedInput"
      | "numberHash"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllEncrypted"
      | "BlendedValue"
      | "EncryptedArray"
      | "EncryptedStruct"
      | "EncryptedValue"
      | "EventNoEncryptedInputs"
  ): EventFragment;

  encodeFunctionData(functionFragment: "eAddress", values?: undefined): string;
  encodeFunctionData(functionFragment: "eBool", values?: undefined): string;
  encodeFunctionData(functionFragment: "eNumber", values?: undefined): string;
  encodeFunctionData(functionFragment: "eUint128", values?: undefined): string;
  encodeFunctionData(functionFragment: "eUint16", values?: undefined): string;
  encodeFunctionData(functionFragment: "eUint32", values?: undefined): string;
  encodeFunctionData(functionFragment: "eUint64", values?: undefined): string;
  encodeFunctionData(functionFragment: "eUint8", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fnAllEncryptedInputs",
    values: [
      InEuint8Struct,
      InEuint16Struct,
      InEuint32Struct,
      InEuint64Struct,
      InEuint128Struct,
      InEboolStruct,
      InEaddressStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fnArrayContainsEncryptedInput",
    values: [InEuint32Struct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fnBlendedInputsIncludingEncryptedInput",
    values: [BigNumberish, InEuint32Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "fnEncryptedInput",
    values: [InEuint32Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "fnNoEncryptedInputs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fnReturnAllEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnReturnBlendedIncludingEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnReturnEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnReturnEncryptedArray",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnReturnEncryptedStruct",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnReturnNoEncrypted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fnStructContainsEncryptedInput",
    values: [ABITest.ContainsEncryptedInputStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "fnTupleContainsEncryptedInput",
    values: [[InEuint32Struct, InEuint32Struct]]
  ): string;
  encodeFunctionData(
    functionFragment: "numberHash",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "eAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eNumber", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eUint128", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eUint16", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eUint32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eUint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eUint8", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fnAllEncryptedInputs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnArrayContainsEncryptedInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnBlendedInputsIncludingEncryptedInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnEncryptedInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnNoEncryptedInputs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnReturnAllEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnReturnBlendedIncludingEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnReturnEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnReturnEncryptedArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnReturnEncryptedStruct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnReturnNoEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnStructContainsEncryptedInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fnTupleContainsEncryptedInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "numberHash", data: BytesLike): Result;
}

export namespace AllEncryptedEvent {
  export type InputTuple = [
    arg0: BytesLike,
    arg1: BytesLike,
    arg2: BytesLike,
    arg3: BytesLike,
    arg4: BytesLike,
    arg5: BytesLike,
    arg6: BytesLike
  ];
  export type OutputTuple = [
    arg0: string,
    arg1: string,
    arg2: string,
    arg3: string,
    arg4: string,
    arg5: string,
    arg6: string
  ];
  export interface OutputObject {
    arg0: string;
    arg1: string;
    arg2: string;
    arg3: string;
    arg4: string;
    arg5: string;
    arg6: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlendedValueEvent {
  export type InputTuple = [value: BigNumberish, encryptedValue: BytesLike];
  export type OutputTuple = [value: bigint, encryptedValue: string];
  export interface OutputObject {
    value: bigint;
    encryptedValue: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedArrayEvent {
  export type InputTuple = [value: BytesLike[]];
  export type OutputTuple = [value: string[]];
  export interface OutputObject {
    value: string[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedStructEvent {
  export type InputTuple = [value: ABITest.ContainsEncryptedResultStruct];
  export type OutputTuple = [
    value: ABITest.ContainsEncryptedResultStructOutput
  ];
  export interface OutputObject {
    value: ABITest.ContainsEncryptedResultStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedValueEvent {
  export type InputTuple = [value: BytesLike];
  export type OutputTuple = [value: string];
  export interface OutputObject {
    value: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EventNoEncryptedInputsEvent {
  export type InputTuple = [value: BigNumberish];
  export type OutputTuple = [value: bigint];
  export interface OutputObject {
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ABITest extends BaseContract {
  connect(runner?: ContractRunner | null): ABITest;
  waitForDeployment(): Promise<this>;

  interface: ABITestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  eAddress: TypedContractMethod<[], [string], "view">;

  eBool: TypedContractMethod<[], [string], "view">;

  eNumber: TypedContractMethod<[], [string], "view">;

  eUint128: TypedContractMethod<[], [string], "view">;

  eUint16: TypedContractMethod<[], [string], "view">;

  eUint32: TypedContractMethod<[], [string], "view">;

  eUint64: TypedContractMethod<[], [string], "view">;

  eUint8: TypedContractMethod<[], [string], "view">;

  fnAllEncryptedInputs: TypedContractMethod<
    [
      inEuint8: InEuint8Struct,
      inEuint16: InEuint16Struct,
      inEuint32: InEuint32Struct,
      inEuint64: InEuint64Struct,
      inEuint128: InEuint128Struct,
      inEbool: InEboolStruct,
      inEaddress: InEaddressStruct
    ],
    [void],
    "nonpayable"
  >;

  fnArrayContainsEncryptedInput: TypedContractMethod<
    [inEuint32Array: InEuint32Struct[]],
    [void],
    "nonpayable"
  >;

  fnBlendedInputsIncludingEncryptedInput: TypedContractMethod<
    [value: BigNumberish, inNumber: InEuint32Struct],
    [void],
    "nonpayable"
  >;

  fnEncryptedInput: TypedContractMethod<
    [inNumber: InEuint32Struct],
    [void],
    "nonpayable"
  >;

  fnNoEncryptedInputs: TypedContractMethod<
    [value: BigNumberish],
    [void],
    "nonpayable"
  >;

  fnReturnAllEncrypted: TypedContractMethod<
    [],
    [[string, string, string, string, string, string, string]],
    "view"
  >;

  fnReturnBlendedIncludingEncrypted: TypedContractMethod<
    [],
    [[bigint, string]],
    "view"
  >;

  fnReturnEncrypted: TypedContractMethod<[], [string], "view">;

  fnReturnEncryptedArray: TypedContractMethod<[], [string[]], "view">;

  fnReturnEncryptedStruct: TypedContractMethod<
    [],
    [ABITest.ContainsEncryptedResultStructOutput],
    "view"
  >;

  fnReturnNoEncrypted: TypedContractMethod<[], [bigint], "view">;

  fnStructContainsEncryptedInput: TypedContractMethod<
    [containsEncryptedInput: ABITest.ContainsEncryptedInputStruct],
    [void],
    "nonpayable"
  >;

  fnTupleContainsEncryptedInput: TypedContractMethod<
    [inEuint32Array: [InEuint32Struct, InEuint32Struct]],
    [void],
    "nonpayable"
  >;

  numberHash: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "eAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eBool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eNumber"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eUint128"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eUint16"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eUint32"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eUint64"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "eUint8"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fnAllEncryptedInputs"
  ): TypedContractMethod<
    [
      inEuint8: InEuint8Struct,
      inEuint16: InEuint16Struct,
      inEuint32: InEuint32Struct,
      inEuint64: InEuint64Struct,
      inEuint128: InEuint128Struct,
      inEbool: InEboolStruct,
      inEaddress: InEaddressStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fnArrayContainsEncryptedInput"
  ): TypedContractMethod<
    [inEuint32Array: InEuint32Struct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fnBlendedInputsIncludingEncryptedInput"
  ): TypedContractMethod<
    [value: BigNumberish, inNumber: InEuint32Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fnEncryptedInput"
  ): TypedContractMethod<[inNumber: InEuint32Struct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fnNoEncryptedInputs"
  ): TypedContractMethod<[value: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fnReturnAllEncrypted"
  ): TypedContractMethod<
    [],
    [[string, string, string, string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "fnReturnBlendedIncludingEncrypted"
  ): TypedContractMethod<[], [[bigint, string]], "view">;
  getFunction(
    nameOrSignature: "fnReturnEncrypted"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fnReturnEncryptedArray"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "fnReturnEncryptedStruct"
  ): TypedContractMethod<
    [],
    [ABITest.ContainsEncryptedResultStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "fnReturnNoEncrypted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fnStructContainsEncryptedInput"
  ): TypedContractMethod<
    [containsEncryptedInput: ABITest.ContainsEncryptedInputStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fnTupleContainsEncryptedInput"
  ): TypedContractMethod<
    [inEuint32Array: [InEuint32Struct, InEuint32Struct]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "numberHash"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AllEncrypted"
  ): TypedContractEvent<
    AllEncryptedEvent.InputTuple,
    AllEncryptedEvent.OutputTuple,
    AllEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "BlendedValue"
  ): TypedContractEvent<
    BlendedValueEvent.InputTuple,
    BlendedValueEvent.OutputTuple,
    BlendedValueEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedArray"
  ): TypedContractEvent<
    EncryptedArrayEvent.InputTuple,
    EncryptedArrayEvent.OutputTuple,
    EncryptedArrayEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedStruct"
  ): TypedContractEvent<
    EncryptedStructEvent.InputTuple,
    EncryptedStructEvent.OutputTuple,
    EncryptedStructEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedValue"
  ): TypedContractEvent<
    EncryptedValueEvent.InputTuple,
    EncryptedValueEvent.OutputTuple,
    EncryptedValueEvent.OutputObject
  >;
  getEvent(
    key: "EventNoEncryptedInputs"
  ): TypedContractEvent<
    EventNoEncryptedInputsEvent.InputTuple,
    EventNoEncryptedInputsEvent.OutputTuple,
    EventNoEncryptedInputsEvent.OutputObject
  >;

  filters: {
    "AllEncrypted(bytes32,bytes32,bytes32,bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      AllEncryptedEvent.InputTuple,
      AllEncryptedEvent.OutputTuple,
      AllEncryptedEvent.OutputObject
    >;
    AllEncrypted: TypedContractEvent<
      AllEncryptedEvent.InputTuple,
      AllEncryptedEvent.OutputTuple,
      AllEncryptedEvent.OutputObject
    >;

    "BlendedValue(uint256,bytes32)": TypedContractEvent<
      BlendedValueEvent.InputTuple,
      BlendedValueEvent.OutputTuple,
      BlendedValueEvent.OutputObject
    >;
    BlendedValue: TypedContractEvent<
      BlendedValueEvent.InputTuple,
      BlendedValueEvent.OutputTuple,
      BlendedValueEvent.OutputObject
    >;

    "EncryptedArray(bytes32[])": TypedContractEvent<
      EncryptedArrayEvent.InputTuple,
      EncryptedArrayEvent.OutputTuple,
      EncryptedArrayEvent.OutputObject
    >;
    EncryptedArray: TypedContractEvent<
      EncryptedArrayEvent.InputTuple,
      EncryptedArrayEvent.OutputTuple,
      EncryptedArrayEvent.OutputObject
    >;

    "EncryptedStruct(tuple)": TypedContractEvent<
      EncryptedStructEvent.InputTuple,
      EncryptedStructEvent.OutputTuple,
      EncryptedStructEvent.OutputObject
    >;
    EncryptedStruct: TypedContractEvent<
      EncryptedStructEvent.InputTuple,
      EncryptedStructEvent.OutputTuple,
      EncryptedStructEvent.OutputObject
    >;

    "EncryptedValue(bytes32)": TypedContractEvent<
      EncryptedValueEvent.InputTuple,
      EncryptedValueEvent.OutputTuple,
      EncryptedValueEvent.OutputObject
    >;
    EncryptedValue: TypedContractEvent<
      EncryptedValueEvent.InputTuple,
      EncryptedValueEvent.OutputTuple,
      EncryptedValueEvent.OutputObject
    >;

    "EventNoEncryptedInputs(uint8)": TypedContractEvent<
      EventNoEncryptedInputsEvent.InputTuple,
      EventNoEncryptedInputsEvent.OutputTuple,
      EventNoEncryptedInputsEvent.OutputObject
    >;
    EventNoEncryptedInputs: TypedContractEvent<
      EventNoEncryptedInputsEvent.InputTuple,
      EventNoEncryptedInputsEvent.OutputTuple,
      EventNoEncryptedInputsEvent.OutputObject
    >;
  };
}
